version: 2.1

defaults: &defaults

aliases:
  - &docker_environment
    - image: cimg/base:stable
  - &checkout
    path: ~/opennms-container
  - &build_container
    name: Building Container Image and Push
    command: ~/opennms-container/.circleci/build.sh
  - &registry_login
    name: Login Container Registry
    command: docker login -u "${DOCKERHUB_LOGIN}" -p "${DOCKERHUB_PASS}"
  - &common_environment
    docker: *docker_environment
    resource_class: small
  - &build
    <<: *common_environment
    steps:
      - build:
          persist: false
  - &build_persist
    <<: *common_environment
    steps:
      - build:
          persist: true

commands:
  build:
    parameters:
      persist:
        type: boolean
        default: false
    steps:
      - checkout: *checkout
      - setup_remote_docker
      - run: *registry_login
      - attach_workspace:
          at: ~/
      - run: *build_container
      - when:
          condition: << parameters.persist >>
          steps:
            - persist_to_workspace:
                root: ~/
                paths:
                  - opennms-container/.circleci/build-numbers
                  - opennms-container/projects
      - store_artifacts:
          path: images/image.oci

jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:latest
    resource_class: small
    steps:
      - checkout
      - run:
          name: Shellcheck Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources -e SC2129,SC2001,SC2013

  centos:
    <<: *build_persist
    working_directory: ~/opennms-container/projects/centos
  
  ubuntu:
    <<: *build_persist
    working_directory: ~/opennms-container/projects/ubuntu

  antora:
    <<: *build
    working_directory: ~/opennms-container/projects/antora

  confd:
    <<: *build
    working_directory: ~/opennms-container/projects/confd

  net-snmp:
    <<: *build
    working_directory: ~/opennms-container/projects/net-snmp
  
  isc-dhcp:
    <<: *build
    working_directory: ~/opennms-container/projects/isc-dhcp

  mini-mail:
    <<: *build
    working_directory: ~/opennms-container/projects/mini-mail

  gobgp:
    <<: *build
    working_directory: ~/opennms-container/projects/gobgp

  openjdk-8:
    <<: *build_persist
    working_directory: ~/opennms-container/projects/openjdk-8

  openjdk-11:
    <<: *build_persist
    working_directory: ~/opennms-container/projects/openjdk-11

  openjdk-17:
    <<: *build_persist
    working_directory: ~/opennms-container/projects/openjdk-17

  maven-jdk8:
    <<: *build_persist
    working_directory: ~/opennms-container/projects/maven-jdk8

  maven-jdk11:
    <<: *build_persist
    working_directory: ~/opennms-container/projects/maven-jdk11

  maven-jdk17:
    <<: *build_persist
    working_directory: ~/opennms-container/projects/maven-jdk17

  ghr:
    <<: *build
    working_directory: ~/opennms-container/projects/ghr

  gulp:
    <<: *build
    working_directory: ~/opennms-container/projects/gulp

  build-env-jdk8:
    <<: *build
    working_directory: ~/opennms-container/projects/build-env-jdk8

  build-env-jdk11:
    <<: *build
    working_directory: ~/opennms-container/projects/build-env-jdk11

  build-env-jdk17:
    <<: *build
    working_directory: ~/opennms-container/projects/build-env-jdk17

  tomcat:
    <<: *build
    working_directory: ~/opennms-container/projects/tomcat

  debian:
    <<: *build_persist
    working_directory: ~/opennms-container/projects/debian

  debian-openjdk-8:
    <<: *build_persist
    working_directory: ~/opennms-container/projects/debian-openjdk-8

  debian-openjdk-11:
    <<: *build_persist
    working_directory: ~/opennms-container/projects/debian-openjdk-11

  debian-openjdk-17:
    <<: *build_persist
    working_directory: ~/opennms-container/projects/debian-openjdk-17

  debian-build-env-jdk8:
    <<: *build
    working_directory: ~/opennms-container/projects/debian-build-env-jdk8

  debian-build-env-jdk11:
    <<: *build
    working_directory: ~/opennms-container/projects/debian-build-env-jdk11

  debian-build-env-jdk17:
    <<: *build
    working_directory: ~/opennms-container/projects/debian-build-env-jdk17

  circleci-python-openjdk-8:
    <<: *build
    working_directory: ~/opennms-container/projects/circleci-python-openjdk-8

  circleci-python-openjdk-11:
    <<: *build
    working_directory: ~/opennms-container/projects/circleci-python-openjdk-11

  circleci-python-openjdk-17:
    <<: *build
    working_directory: ~/opennms-container/projects/circleci-python-openjdk-17

  circleci-ubuntu-build-env-jdk8:
    <<: *build
    working_directory: ~/opennms-container/projects/circleci-ubuntu-build-env-jdk8

  circleci-ubuntu-build-env-jdk11:
    <<: *build
    working_directory: ~/opennms-container/projects/circleci-ubuntu-build-env-jdk11

  circleci-ubuntu-build-env-jdk17:
    <<: *build
    working_directory: ~/opennms-container/projects/circleci-ubuntu-build-env-jdk17

  snapcraft:
    <<: *build
    working_directory: ~/opennms-container/projects/snapcraft

  yum-repo:
    <<: *build
    working_directory: ~/opennms-container/projects/yum-repo

  gns3-horizon:
    <<: *build
    working_directory: ~/opennms-container/projects/gns3-horizon

  gns3-minion:
    <<: *build
    working_directory: ~/opennms-container/projects/gns3-minion

workflows:
  version: 2
  container_build:
    jobs:
      - shellcheck:
          context:
            - "docker-publish-account"
      - tomcat:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - centos:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - ubuntu:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - antora:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - confd:
          context:
            - "docker-publish-account"
          requires:
            - centos
      - net-snmp:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - isc-dhcp:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - mini-mail:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - gobgp:
          context:
            - "docker-publish-account"
          requires:
            - ubuntu
      - openjdk-8:
          context:
            - "docker-publish-account"
          requires:
            - centos
      - openjdk-11:
          context:
            - "docker-publish-account"
          requires:
            - centos
      - openjdk-17:
          context:
            - "docker-publish-account"
          requires:
            - centos
      - maven-jdk8:
          context:
            - "docker-publish-account"
          requires:
            - openjdk-8
      - maven-jdk11:
          context:
            - "docker-publish-account"
          requires:
            - openjdk-11
      - maven-jdk17:
          context:
            - "docker-publish-account"
          requires:
            - openjdk-17
      - ghr:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - gulp:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - build-env-jdk8:
          context:
            - "docker-publish-account"
          requires:
            - maven-jdk8
      - build-env-jdk11:
          context:
            - "docker-publish-account"
          requires:
            - maven-jdk11
      - build-env-jdk17:
          context:
            - "docker-publish-account"
          requires:
            - maven-jdk17
      - debian:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - debian-openjdk-8:
          context:
            - "docker-publish-account"
          requires:
            - debian
      - debian-openjdk-11:
          context:
            - "docker-publish-account"
          requires:
            - debian
      - debian-openjdk-17:
          context:
            - "docker-publish-account"
          requires:
            - debian
      - debian-build-env-jdk8:
          context:
            - "docker-publish-account"
          requires:
            - debian-openjdk-8
      - debian-build-env-jdk11:
          context:
            - "docker-publish-account"
          requires:
            - debian-openjdk-11
      - debian-build-env-jdk17:
          context:
            - "docker-publish-account"
          requires:
            - debian-openjdk-17
      - circleci-ubuntu-build-env-jdk8:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - circleci-ubuntu-build-env-jdk11:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - circleci-ubuntu-build-env-jdk17:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - circleci-python-openjdk-8:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - circleci-python-openjdk-11:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - circleci-python-openjdk-17:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - snapcraft:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - yum-repo:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - gns3-horizon:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
      - gns3-minion:
          context:
            - "docker-publish-account"
          requires:
            - shellcheck
