version: 2.0

defaults: &defaults

aliases:
  - &docker_environment
    - image: docker:18.06.0-ce-git
  - &checkout
    path: ~/opennms-container
  - &build_container
    name: Building Container Image
    command: ~/opennms-container/.circleci/build.sh
  - &registry_login
    name: Login Container Registry
    command: docker login -u ${CONTAINER_REGISTRY_LOGIN} -p ${CONTAINER_REGISTRY_PASS}
  - &common_steps
    - checkout: *checkout
    - setup_remote_docker
    - run: apk add --no-cache bash
    - run: *registry_login
    - run: *build_container
    - store_artifacts:
        path: images/image.oci
  - &common_environment
    docker: *docker_environment
    steps: *common_steps

jobs:
  shellcheck:
    docker:
      - image: opennms/shellcheck:0.5.0-b1
    steps:
      - checkout
      - run:
          name: Shellcheck Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources -e SC2129,SC2001,SC2013

  centos:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/centos
  
  ubuntu:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/ubuntu

  confd:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/confd

  net-snmp:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/net-snmp
  
  isc-dhcp:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/isc-dhcp

  mini-mail:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/mini-mail

  gobgp:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/gobgp

  openjdk-8:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/openjdk-8

  openjdk-11:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/openjdk-11

  openjdk:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/openjdk

  maven-jdk8:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/maven-jdk8

  maven-jdk11:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/maven-jdk11

  maven-jdk:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/maven-jdk

  netlify-cli:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/netlify-cli

  package-cloud-cli:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/package-cloud-cli

  ghr:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/ghr

  gulp:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/gulp

  shellcheck-image:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/shellcheck

  build-env-jdk8:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/build-env-jdk8

  build-env-jdk11:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/build-env-jdk11

  build-env-jdk:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/build-env-jdk

  tomcat:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/tomcat

  debian:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/debian

  debian-openjdk-8:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/debian-openjdk-8

  debian-openjdk-11:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/debian-openjdk-11

  debian-openjdk:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/debian-openjdk

  debian-build-env-jdk8:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/debian-build-env-jdk8

  debian-build-env-jdk11:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/debian-build-env-jdk11

  debian-build-env-jdk:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/debian-build-env-jdk

  snapcraft:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/snapcraft

  yum-repo:
    <<: *common_environment
    working_directory: ~/opennms-container/projects/yum-repo

workflows:
  version: 2
  container_build:
    jobs:
      - shellcheck
      - tomcat:
          requires:
            - shellcheck
      - centos:
          requires:
            - shellcheck
      - ubuntu:
          requires:
            - shellcheck
      - confd:
          requires:
            - shellcheck
            - centos
      - net-snmp:
          requires:
            - shellcheck
      - isc-dhcp:
          requires:
            - shellcheck
      - mini-mail:
          requires:
            - shellcheck
      - gobgp:
          requires:
            - shellcheck
            - centos
      - openjdk-8:
          requires:
            - shellcheck
            - centos
      - openjdk-11:
          requires:
            - shellcheck
            - centos
      - openjdk:
          requires:
            - shellcheck
            - centos
      - maven-jdk8:
          requires:
            - shellcheck
            - openjdk-8
      - maven-jdk11:
          requires:
            - shellcheck
            - openjdk-11
      - maven-jdk:
          requires:
            - shellcheck
            - openjdk
      - netlify-cli:
          requires:
            - shellcheck
      - package-cloud-cli:
          requires:
            - shellcheck
      - ghr:
          requires:
            - shellcheck
      - gulp:
          requires:
            - shellcheck
      - shellcheck-image:
          requires:
            - shellcheck
      - build-env-jdk8:
          requires:
            - shellcheck
            - maven-jdk8
      - build-env-jdk11:
          requires:
            - shellcheck
            - maven-jdk11
      - build-env-jdk:
          requires:
            - shellcheck
            - maven-jdk
      - debian:
          requires:
            - shellcheck
      - debian-openjdk-8:
          requires:
            - shellcheck
            - debian
      - debian-openjdk-11:
          requires:
            - shellcheck
            - debian
      - debian-openjdk:
          requires:
            - shellcheck
            - debian
      - debian-build-env-jdk8:
          requires:
            - shellcheck
            - debian-openjdk-8
      - debian-build-env-jdk11:
          requires:
            - shellcheck
            - debian-openjdk-11
      - debian-build-env-jdk:
          requires:
            - shellcheck
            - debian-openjdk
      - snapcraft:
          requires:
            - shellcheck
      - yum-repo:
          requires:
            - shellcheck
            